import os

POSITIVE_FOLDER_NAME = "positive"
NEGATIVE_FOLDER_NAME = "negative"
PATIENT_CODE = "chb12"
POSITIVE_PATH = os.path.join(os.getcwd(), *["data", "all", POSITIVE_FOLDER_NAME])
NEGATIVE_PATH = os.path.join(os.getcwd(), *["data", "all", NEGATIVE_FOLDER_NAME])
EEG_SIGNAL_NUMBER = 23
TRAIN_SPLIT = 0.7

OLD_SAMPLE_RATE = 256
NEW_SAMPLE_RATE = 200
WINDOW_IN_SECONDS = 5
WINDOW_SIZE = NEW_SAMPLE_RATE * WINDOW_IN_SECONDS
BATCH_SIZE = 128
CLASSES = 2
